# Generated by Django 3.0.3 on 2020-03-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20200309_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maskedimage',
            old_name='MaskedImage',
            new_name='croppedImage',
        ),
    ]
