# Generated by Django 3.0.3 on 2020-03-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_auto_20200309_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskedimage',
            name='croppedImage',
            field=models.ImageField(upload_to='masked_images', verbose_name='masks'),
        ),
    ]
