# Generated by Django 3.0.3 on 2020-03-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_auto_20200309_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaskedImage',
        ),
    ]
