# Generated by Django 3.0.3 on 2020-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_imagemodel_input_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='input_threshold',
            field=models.DecimalField(decimal_places=1, default=0.7, max_digits=1),
        ),
    ]
